# Generated by Django 5.2.11 on 2026-05-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='pincode',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
