# Generated by Django 5.2.11 on 2026-06-22 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_village_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='village',
            name='pincode',
        ),
    ]
