# Generated by Django 5.2.11 on 2026-08-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('loan_type', models.CharField(choices=[('home_loan', 'Home Loan'), ('property_loan', 'Property Loan'), ('land_loan', 'Land Loan'), ('construction_loan', 'Construction Loan'), ('loan_against_property', 'Loan Against Property')], max_length=50)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tenure_years', models.PositiveIntegerField(blank=True, null=True)),
                ('property_type', models.CharField(blank=True, max_length=100, null=True)),
                ('property_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('property_location', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('salaried', 'Salaried'), ('self_employed', 'Self Employed'), ('business', 'Business'), ('professional', 'Professional'), ('other', 'Other')], max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('work_experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('has_existing_loan', models.BooleanField(default=False)),
                ('existing_emi', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('aadhaar_last_four', models.CharField(blank=True, max_length=4, null=True)),
                ('source', models.CharField(default='website', max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('document_pending', 'Document Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='new', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
