# Generated by Django 5.2.11 on 2026-08-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanenquiry',
            name='aadhaar_last_four',
        ),
        migrations.RemoveField(
            model_name='loanenquiry',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='loanenquiry',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='loanenquiry',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='loanenquiry',
            name='existing_emi',
        ),
        migrations.RemoveField(
            model_name='loanenquiry',
            name='has_existing_loan',
        ),
        migrations.RemoveField(
            model_name='loanenquiry',
            name='pan_number',
        ),
        migrations.RemoveField(
            model_name='loanenquiry',
            name='property_location',
        ),
        migrations.RemoveField(
            model_name='loanenquiry',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='loanenquiry',
            name='property_value',
        ),
        migrations.RemoveField(
            model_name='loanenquiry',
            name='source',
        ),
        migrations.RemoveField(
            model_name='loanenquiry',
            name='work_experience_years',
        ),
    ]
