# Generated by Django 5.2.11 on 2026-04-02 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_address_remove_user_role'),
        ('admin_profile', '0003_uploadimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_profile.admin_role'),
        ),
    ]
