# Generated by Django 5.2.11 on 2026-08-03 10:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'db_table': 'amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('property_type', models.CharField(choices=[('flat', 'Flat / Apartment'), ('villa', 'Villa / Bungalow'), ('plot', 'Plot / Land'), ('commercial', 'Commercial Space'), ('shop', 'Shop / Retail'), ('office', 'Office Space'), ('warehouse', 'Warehouse'), ('other', 'Other')], default='flat', max_length=20, verbose_name='Property Type')),
                ('transaction_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('lease', 'For Lease'), ('pg', 'PG / Hostel')], default='sale', max_length=10, verbose_name='Transaction Type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('active', 'Active'), ('sold', 'Sold'), ('rented', 'Rented'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='draft', max_length=20, verbose_name='Listing Status')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('price_per_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price per Sq. Ft.')),
                ('maintenance_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maintenance Charge')),
                ('booking_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Booking Amount')),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Area (sq. ft.)')),
                ('carpet_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Carpet Area (sq. ft.)')),
                ('built_up_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Built-up Area (sq. ft.)')),
                ('plot_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Plot Area (sq. ft.)')),
                ('bedrooms', models.PositiveIntegerField(default=0, verbose_name='Bedrooms')),
                ('bathrooms', models.PositiveIntegerField(default=0, verbose_name='Bathrooms')),
                ('balconies', models.PositiveIntegerField(default=0, verbose_name='Balconies')),
                ('kitchens', models.PositiveIntegerField(default=1, verbose_name='Kitchens')),
                ('total_floors', models.PositiveIntegerField(default=1, verbose_name='Total Floors')),
                ('floor_number', models.PositiveIntegerField(default=1, verbose_name='Floor Number')),
                ('parking_count', models.PositiveIntegerField(default=0, verbose_name='Parking Count')),
                ('parking_type', models.CharField(blank=True, choices=[('open', 'Open Parking'), ('covered', 'Covered Parking'), ('basement', 'Basement Parking'), ('multiple', 'Multiple')], max_length=20, null=True, verbose_name='Parking Type')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('area', models.CharField(max_length=100, verbose_name='Area')),
                ('address', models.TextField(verbose_name='Full Address')),
                ('landmark', models.CharField(blank=True, max_length=255, verbose_name='Landmark')),
                ('pincode', models.CharField(max_length=10, verbose_name='Pincode')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='Additional Features')),
                ('owner_name', models.CharField(max_length=255, verbose_name='Owner Name')),
                ('owner_contact', models.CharField(max_length=15, verbose_name='Owner Contact')),
                ('owner_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Owner Email')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Views Count')),
                ('enquiry_count', models.PositiveIntegerField(default=0, verbose_name='Enquiry Count')),
                ('favorite_count', models.PositiveIntegerField(default=0, verbose_name='Favorite Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='Expiry Date')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('is_furnished', models.BooleanField(default=False, verbose_name='Is Furnished')),
                ('is_negotiable', models.BooleanField(default=True, verbose_name='Is Negotiable')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('amenities', models.ManyToManyField(blank=True, related_name='properties', to='real_estate.amenity', verbose_name='Amenities')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('sale_deed', 'Sale Deed'), ('agreement', 'Agreement'), ('noc', 'NOC'), ('approval', 'Approval'), ('registration', 'Registration'), ('other', 'Other')], default='other', max_length=20, verbose_name='Document Type')),
                ('file', models.URLField()),
                ('title', models.CharField(max_length=255, verbose_name='Document Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='real_estate.property', verbose_name='Property')),
            ],
            options={
                'verbose_name': 'Property Document',
                'verbose_name_plural': 'Property Documents',
                'db_table': 'property_documents',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_s3_key', models.ImageField(upload_to='properties/%Y/%m/%d/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Is Primary Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='real_estate.property', verbose_name='Property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
                'db_table': 'property_images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_s3_key', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Video Title')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured Video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='real_estate.property', verbose_name='Property')),
            ],
            options={
                'verbose_name': 'Property Video',
                'verbose_name_plural': 'Property Videos',
                'db_table': 'property_videos',
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'transaction_type'], name='properties_status_2ec93a_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'area'], name='properties_city_f38e71_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price'], name='properties_price_aa33af_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type'], name='properties_propert_f38ecc_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['bedrooms', 'bathrooms'], name='properties_bedroom_2aae3d_idx'),
        ),
    ]
