# Generated by Django 5.2.11 on 2026-08-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydocument',
            name='file',
            field=models.URLField(max_length=1000, verbose_name='Document File URL'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image_s3_key',
            field=models.URLField(max_length=1000, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='propertyvideo',
            name='video_s3_key',
            field=models.URLField(max_length=1000, verbose_name='Video URL'),
        ),
    ]
