# Generated by Django 5.2.11 on 2026-08-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_propertyenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='referral_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Referral Code'),
        ),
    ]
