# Generated by Django 5.2.11 on 2026-08-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0005_alter_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status_approve',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('active', 'Active'), ('sold', 'Sold'), ('rented', 'Rented'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='draft', max_length=20, verbose_name='Listing Status'),
        ),
    ]
