# Generated by Django 5.2.11 on 2026-08-07 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0006_property_status_approve_alter_property_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='agent',
        ),
    ]
