# Generated by Django 5.2.11 on 2026-08-07 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0008_property_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='slug',
        ),
    ]
