# Generated by Django 5.2.11 on 2026-08-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0010_alter_property_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('purpose', models.CharField(blank=True, max_length=20, null=True)),
                ('property_type', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('bhk', models.IntegerField(blank=True, null=True)),
                ('min_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
