# Generated by Django 5.2.11 on 2026-09-04 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0013_channelpartner_propertysalecommission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('purpose', models.CharField(blank=True, max_length=20, null=True)),
                ('property_type', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('bhk', models.IntegerField(blank=True, null=True)),
                ('min_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('current_step', models.CharField(default='purpose', max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='propertysalecommission',
            name='channel_partner',
        ),
        migrations.RemoveField(
            model_name='propertysalecommission',
            name='property',
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='real_estate.chatsession')),
            ],
        ),
        migrations.DeleteModel(
            name='ChannelPartner',
        ),
        migrations.DeleteModel(
            name='PropertySaleCommission',
        ),
    ]
