# Generated by Django 5.2.11 on 2026-09-04 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0015_realestatechannelpartner'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstatePropertyCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cp_commission_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cp_commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('business_partner_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('business_partner_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cp_final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_commissions', to='real_estate.realestatechannelpartner')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='real_estate.property')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('property', 'channel_partner'), name='unique_property_channel_partner')],
            },
        ),
    ]
