# Generated by Django 5.2.11 on 2026-09-07 05:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0016_realestatepropertycommission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_info', models.TextField(blank=True, null=True)),
                ('logo', models.URLField(blank=True, max_length=500, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'builders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FlatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_type', models.CharField(max_length=50)),
                ('area_sqft', models.DecimalField(decimal_places=2, max_digits=12)),
                ('carpet_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('built_up_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('balcony_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('balconies', models.PositiveIntegerField(default=0)),
                ('kitchens', models.PositiveIntegerField(default=1)),
                ('parking_count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'flat_types',
                'ordering': ['flat_type'],
            },
        ),
        migrations.CreateModel(
            name='FloorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.PositiveIntegerField()),
                ('floor_name', models.CharField(blank=True, max_length=100)),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('available_units', models.PositiveIntegerField(default=0)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'floor_infos',
                'ordering': ['floor_number'],
            },
        ),
        migrations.CreateModel(
            name='PricingSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_per_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('booking_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=5, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('payment_schedule', models.JSONField(blank=True, default=dict)),
                ('additional_charges', models.JSONField(blank=True, default=dict)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pricing_slabs',
                'ordering': ['floor__floor_number', 'flat_type__flat_type'],
            },
        ),
        migrations.CreateModel(
            name='RealEstateCommissionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUSINESS_PARTNER_COMMISSION', 'Business Partner Commission')], default='BUSINESS_PARTNER_COMMISSION', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('BANK_TRANSFER', 'Bank Transfer'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('IMPS', 'IMPS'), ('CHEQUE', 'Cheque'), ('CASH', 'Cash')], max_length=30)),
                ('gateway', models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('MANUAL', 'Manual')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20)),
                ('razorpay_payout_id', models.CharField(blank=True, max_length=100, null=True)),
                ('utr', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_id', models.CharField(max_length=100, unique=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile_picture', models.URLField(blank=True, max_length=500, null=True)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('social_media', models.JSONField(blank=True, default=dict)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('working_hours', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sellers',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='amenity',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='propertydocument',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['display_order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='propertyvideo',
            options={'ordering': ['display_order', 'created_at']},
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='properties_price_aa33af_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='properties_bedroom_2aae3d_idx',
        ),
        migrations.RemoveField(
            model_name='property',
            name='balconies',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='booking_amount',
        ),
        migrations.RemoveField(
            model_name='property',
            name='built_up_area',
        ),
        migrations.RemoveField(
            model_name='property',
            name='carpet_area',
        ),
        migrations.RemoveField(
            model_name='property',
            name='floor_number',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_furnished',
        ),
        migrations.RemoveField(
            model_name='property',
            name='kitchens',
        ),
        migrations.RemoveField(
            model_name='property',
            name='maintenance_charge',
        ),
        migrations.RemoveField(
            model_name='property',
            name='owner_contact',
        ),
        migrations.RemoveField(
            model_name='property',
            name='owner_email',
        ),
        migrations.RemoveField(
            model_name='property',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='property',
            name='parking_count',
        ),
        migrations.RemoveField(
            model_name='property',
            name='parking_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price_per_sqft',
        ),
        migrations.RemoveField(
            model_name='property',
            name='status_approve',
        ),
        migrations.RemoveField(
            model_name='propertydocument',
            name='file',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='order',
        ),
        migrations.AddField(
            model_name='amenity',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='completion_percentage',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='property',
            name='google_location_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='is_under_construction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='possession_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rera_additional_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='rera_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rera_qr_code',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rera_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='total_towers',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='file_url',
            field=models.URLField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='image_type',
            field=models.CharField(choices=[('exterior', 'Exterior'), ('interior', 'Interior'), ('floor_plan', 'Floor Plan'), ('layout', 'Layout'), ('kitchen', 'Kitchen'), ('bedroom', 'Bedroom'), ('bathroom', 'Bathroom'), ('amenity', 'Amenity'), ('plot', 'Plot'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='properties', to='real_estate.amenity'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='enquiry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='favorite_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='features',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_negotiable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='landmark',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='plot_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('flat', 'Flat / Apartment'), ('villa', 'Villa / Bungalow'), ('plot', 'Plot / Land'), ('commercial', 'Commercial Space'), ('shop', 'Shop / Retail'), ('office', 'Office Space'), ('warehouse', 'Warehouse'), ('other', 'Other')], default='flat', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='referral_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('active', 'Active'), ('sold', 'Sold'), ('rented', 'Rented'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_area',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_floors',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('lease', 'For Lease'), ('pg', 'PG / Hostel')], default='sale', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='document_type',
            field=models.CharField(choices=[('sale_deed', 'Sale Deed'), ('agreement', 'Agreement'), ('noc', 'NOC'), ('approval', 'Approval'), ('registration', 'Registration'), ('rera', 'RERA Document'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='real_estate.property'),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image_s3_key',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='real_estate.property'),
        ),
        migrations.AlterField(
            model_name='propertyvideo',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='propertyvideo',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='real_estate.property'),
        ),
        migrations.AlterField(
            model_name='propertyvideo',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propertyvideo',
            name='video_s3_key',
            field=models.URLField(max_length=1000),
        ),
        migrations.AddField(
            model_name='property',
            name='builder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='real_estate.builder'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['builder'], name='properties_builder_86ac72_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['rera_number'], name='properties_rera_nu_ab4c6d_idx'),
        ),
        migrations.AddField(
            model_name='flattype',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat_types', to='real_estate.property'),
        ),
        migrations.AddField(
            model_name='floorinfo',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='real_estate.property'),
        ),
        migrations.AddField(
            model_name='pricingslab',
            name='flat_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_slabs', to='real_estate.flattype'),
        ),
        migrations.AddField(
            model_name='pricingslab',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_slabs', to='real_estate.floorinfo'),
        ),
        migrations.AddField(
            model_name='pricingslab',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_slabs', to='real_estate.property'),
        ),
        migrations.AddField(
            model_name='realestatecommissiontransaction',
            name='commission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='real_estate.realestatepropertycommission'),
        ),
        migrations.AddField(
            model_name='seller',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='real_estate.property'),
        ),
        migrations.AddConstraint(
            model_name='flattype',
            constraint=models.UniqueConstraint(fields=('property', 'flat_type'), name='unique_property_flat_type'),
        ),
        migrations.AddConstraint(
            model_name='floorinfo',
            constraint=models.UniqueConstraint(fields=('property', 'floor_number'), name='unique_property_floor'),
        ),
        migrations.AddConstraint(
            model_name='pricingslab',
            constraint=models.UniqueConstraint(fields=('property', 'floor', 'flat_type'), name='unique_property_floor_flat'),
        ),
    ]
