# Generated by Django 5.2.11 on 2026-09-07 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0017_builder_flattype_floorinfo_pricingslab_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyenquiry',
            name='assigned_agent',
        ),
        migrations.AddField(
            model_name='propertyenquiry',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyenquiry',
            name='assigned_channel_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to='real_estate.realestatechannelpartner'),
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
