# Generated by Django 5.2.11 on 2026-09-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0019_property_status_approved_propertyviewpayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyviewpayment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='propertyviewpayment',
            old_name='transaction_id',
            new_name='razorpay_signature',
        ),
        migrations.AddField(
            model_name='propertyviewpayment',
            name='razorpay_order_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyviewpayment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertyviewpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='propertyviewpayment',
            name='payment_status',
            field=models.CharField(choices=[('created', 'Created'), ('success', 'Success'), ('failed', 'Failed')], default='created', max_length=20),
        ),
        migrations.AlterModelTable(
            name='propertyviewpayment',
            table='property_view_payments',
        ),
    ]
