# Generated by Django 5.2.11 on 2026-09-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0020_alter_propertyviewpayment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='builder',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='builder',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='builder',
            name='longitude',
        ),
        migrations.AddField(
            model_name='builder',
            name='logo_s3_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='PropertyViewPayment',
        ),
    ]
