# Generated by Django 5.2.11 on 2026-09-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0021_remove_builder_latitude_remove_builder_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_condition',
            field=models.CharField(choices=[('new', 'New Property'), ('resale', 'Old / Resale Property')], default='new', max_length=20),
        ),
    ]
