# Generated by Django 5.2.11 on 2026-09-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0022_property_property_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ready_to_move',
            field=models.BooleanField(default=False),
        ),
    ]
