# Generated by Django 5.2.11 on 2026-09-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0023_property_ready_to_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyenquiry',
            name='budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='propertyenquiry',
            name='budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='propertyenquiry',
            name='flat_type',
            field=models.CharField(blank=True, choices=[('studio', 'Studio'), ('1_bhk', '1 BHK'), ('2_bhk', '2 BHK'), ('3_bhk', '3 BHK'), ('4_bhk', '4 BHK'), ('5_bhk', '5 BHK'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
