# Generated by Django 5.2.11 on 2026-09-13 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0020_rename_referral_code_productenquiry_enquiry_referral_code_and_more'),
        ('real_estate', '0024_propertyenquiry_budget_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyenquiry',
            name='assigned_channel_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to='enquiry.marketingpartner'),
        ),
    ]
