# Generated by Django 5.2.11 on 2026-09-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0025_alter_propertyenquiry_assigned_channel_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyenquiry',
            name='meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyenquiry',
            name='meeting_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertyenquiry',
            name='meeting_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyenquiry',
            name='meeting_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyenquiry',
            name='meeting_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyenquiry',
            name='whatsapp_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyenquiry',
            name='whatsapp_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyenquiry',
            name='whatsapp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
