# Generated by Django 5.2.11 on 2026-09-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0026_propertyenquiry_meeting_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyenquiry',
            name='meeting_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyenquiry',
            name='meeting_outcome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyenquiry',
            name='meeting_status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('customer_not_attended', 'Customer Not Attended'), ('partner_not_attended', 'Partner Not Attended'), ('cancelled', 'Cancelled')], default='scheduled', max_length=30),
        ),
        migrations.AddField(
            model_name='propertyenquiry',
            name='next_followup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
