# Generated by Django 5.2.11 on 2026-09-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0027_propertyenquiry_meeting_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flattype',
            name='area_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
