# Generated by Django 5.2.11 on 2026-09-20 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0028_alter_flattype_area_sqft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='total_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
