# Generated by Django 5.2.11 on 2026-09-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0029_alter_property_total_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySubscriptionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_days', models.PositiveIntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'property_subscription_settings',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='free_days',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='property',
            name='free_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('admin', 'Admin Panel')], default='website', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='subscription_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='subscription_required',
            field=models.BooleanField(default=False),
        ),
    ]
