# Generated by Django 5.2.11 on 2026-09-20 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0030_propertysubscriptionsetting_property_free_days_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flattype',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='flattype',
            name='unique_property_flat_type',
        ),
    ]
