# Generated by Django 5.2.11 on 2026-09-21 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0020_rename_referral_code_productenquiry_enquiry_referral_code_and_more'),
        ('real_estate', '0031_alter_flattype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='marketing_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='enquiry.marketingpartner'),
        ),
    ]
