# Generated by Django 5.2.11 on 2026-09-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0032_property_marketing_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='free_days',
            field=models.PositiveIntegerField(blank=True, default=15, null=True),
        ),
    ]
