# Generated by Django 5.2.11 on 2026-09-18 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BazaarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bazaar_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BazaarPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_days', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bazaar_plans',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='BazaarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_listing_free', models.BooleanField(default=True)),
                ('free_listing_days', models.PositiveIntegerField(default=15)),
                ('payment_required_after_expiry', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bazaar_settings',
            },
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.CreateModel(
            name='BazaarListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_negotiable', models.BooleanField(default=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('used', 'Used')], default='used', max_length=30)),
                ('seller_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business')], default='individual', max_length=30)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('sold', 'Sold'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('favourites_count', models.PositiveIntegerField(default=0)),
                ('is_first_listing', models.BooleanField(default=False)),
                ('free_period_days', models.PositiveIntegerField(default=0)),
                ('active_from', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='olx.bazaarcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bazaar_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bazaar_listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BazaarListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_s3_key', models.CharField(max_length=500)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='olx.bazaarlisting')),
            ],
            options={
                'db_table': 'bazaar_listing_images',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BazaarPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=150, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=150, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='olx.bazaarlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bazaar_payments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='olx.bazaarplan')),
            ],
            options={
                'db_table': 'bazaar_payments',
            },
        ),
        migrations.CreateModel(
            name='BazaarPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='olx.bazaarcategory')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_pricing', to='olx.bazaarplan')),
            ],
            options={
                'db_table': 'bazaar_pricing',
            },
        ),
        migrations.CreateModel(
            name='BazaarRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_expiry', models.DateTimeField()),
                ('new_expiry', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='olx.bazaarlisting')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='renewal', to='olx.bazaarpayment')),
            ],
            options={
                'db_table': 'bazaar_renewals',
            },
        ),
        migrations.CreateModel(
            name='BazaarSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='olx.bazaarcategory')),
            ],
            options={
                'db_table': 'bazaar_subcategories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='bazaarlisting',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='olx.bazaarsubcategory'),
        ),
        migrations.CreateModel(
            name='BazaarAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('key', models.SlugField(max_length=150)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select'), ('boolean', 'Boolean'), ('year', 'Year')], default='text', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='olx.bazaarcategory')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='olx.bazaarsubcategory')),
            ],
            options={
                'db_table': 'bazaar_attributes',
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.AddConstraint(
            model_name='bazaarpricing',
            constraint=models.UniqueConstraint(fields=('category', 'plan'), name='unique_bazaar_category_plan'),
        ),
        migrations.AddConstraint(
            model_name='bazaarsubcategory',
            constraint=models.UniqueConstraint(fields=('category', 'slug'), name='unique_bazaar_subcategory'),
        ),
        migrations.AddIndex(
            model_name='bazaarlisting',
            index=models.Index(fields=['category', 'status'], name='bazaar_list_categor_4c11b2_idx'),
        ),
        migrations.AddIndex(
            model_name='bazaarlisting',
            index=models.Index(fields=['subcategory', 'status'], name='bazaar_list_subcate_a3fce7_idx'),
        ),
        migrations.AddIndex(
            model_name='bazaarlisting',
            index=models.Index(fields=['city', 'status'], name='bazaar_list_city_1a6948_idx'),
        ),
        migrations.AddIndex(
            model_name='bazaarlisting',
            index=models.Index(fields=['expires_at'], name='bazaar_list_expires_55ca74_idx'),
        ),
    ]
