# Generated by Django 5.2.11 on 2026-09-18 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0002_bazaarcategory_bazaarplan_bazaarsettings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bazaarcategory',
            name='image',
        ),
    ]
