# Generated by Django 5.2.11 on 2026-09-23 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0003_remove_bazaarcategory_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bazaarplan',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.RemoveField(
            model_name='bazaarplan',
            name='price',
        ),
    ]
