# Generated by Django 5.2.11 on 2026-06-08 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Franchicies', '0001_initial'),
        ('company', '0009_companypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='franchises', to='company.company'),
            preserve_default=False,
        ),
    ]
