# Generated by Django 5.2.11 on 2026-06-15 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Franchicies', '0002_franchise_company'),
        ('company', '0011_company_accept_terms_conditions'),
        ('product', '0021_product_gst_percent_alter_product_hsn_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchisePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='franchise_plans', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='FranchisePlanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('franchise_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_products', to='Franchicies.franchiseplan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
