# Generated by Django 5.2.11 on 2026-06-15 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Franchicies', '0003_franchiseplan_franchiseplanproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchisePlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilogram'), ('gm', 'Gram'), ('ltr', 'Litre'), ('ml', 'Millilitre'), ('box', 'Box'), ('packet', 'Packet'), ('set', 'Set')], max_length=20)),
                ('franchise_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Franchicies.franchiseplan')),
            ],
        ),
        migrations.DeleteModel(
            name='FranchisePlanProduct',
        ),
    ]
