# Generated by Django 5.2.11 on 2026-07-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Franchicies', '0005_franchiseplan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='franchise_referral_code',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
