# Generated by Django 5.2.11 on 2026-07-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Franchicies', '0006_franchise_franchise_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='franchise_referral_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
