# Generated by Django 5.2.11 on 2026-07-22 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Franchicies', '0007_alter_franchise_franchise_referral_code'),
        ('product', '0023_product_is_franchise_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='franchises', to='product.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='franchiseplan',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='franchise_plans', to='product.product'),
            preserve_default=False,
        ),
    ]
