# Generated by Django 5.2.11 on 2026-07-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Franchicies', '0008_franchise_product_franchiseplan_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='franchise_referral_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
