# Generated by Django 5.2.11 on 2026-07-24 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Franchicies', '0009_alter_franchise_franchise_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchise',
            name='commission_percentage',
        ),
        migrations.AddField(
            model_name='franchise',
            name='FranchisePlan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='franchises', to='Franchicies.franchiseplan'),
            preserve_default=False,
        ),
    ]
