# Generated by Django 5.2.11 on 2026-07-24 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Franchicies', '0010_remove_franchise_commission_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchise',
            name='franchise_code',
        ),
    ]
