# Generated by Django 5.2.11 on 2026-03-26 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_number', models.CharField(max_length=100, unique=True)),
                ('agreement_start_date', models.DateField()),
                ('agreement_end_date', models.DateField()),
                ('company_owner_name', models.CharField(max_length=255)),
                ('company_owner_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(max_length=20)),
                ('company_address', models.TextField()),
                ('profit_share_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('additional_points', models.TextField()),
                ('qnx_mart_representative', models.CharField(max_length=255)),
                ('qnx_mart_sign_s3_key', models.CharField(blank=True, max_length=500, null=True)),
                ('company_sign_s3_key', models.CharField(blank=True, max_length=500, null=True)),
                ('qnx_mart_picture_s3_key', models.CharField(blank=True, max_length=500, null=True)),
                ('company_picture_s3_key', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='company.company')),
            ],
        ),
    ]
