# Generated by Django 5.2.11 on 2026-04-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='company_owner_email',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='company_phone',
        ),
        migrations.AddField(
            model_name='agreement',
            name='global_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='owner_adhar_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='owner_pan_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='selle_radhar_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='seller_pan_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
