# Generated by Django 5.2.11 on 2026-05-15 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0002_remove_agreement_company_owner_email_and_more'),
        ('company', '0007_company_payment_id_company_payment_status'),
        ('enquiry', '0010_remove_uenquiry_is_sent_to_company_and_more'),
        ('product', '0021_product_gst_percent_alter_product_hsn_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='agreement_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='apply_on_all_products',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='marketing_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='enquiry.marketingpartner'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='additional_points',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='company.company'),
        ),
        migrations.CreateModel(
            name='AgreementProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_products', to='agreement.agreement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_products', to='product.product')),
            ],
        ),
    ]
