# Generated by Django 5.2.11 on 2026-05-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0004_agreement_approved_at_agreement_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='qnx_mart_representative',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
