# Generated by Django 5.2.11 on 2026-06-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0005_alter_agreement_qnx_mart_representative'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='uploaded_agreement_pdf_s3_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
