# Generated by Django 5.2.11 on 2026-07-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0006_agreement_uploaded_agreement_pdf_s3_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='selle_radhar_number',
        ),
        migrations.AddField(
            model_name='agreement',
            name='seller_adhar_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='selling_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
