# Generated by Django 5.2.11 on 2026-09-16 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0007_remove_agreement_selle_radhar_number_and_more'),
        ('company', '0022_alter_company_ian_no'),
        ('enquiry', '0020_rename_referral_code_productenquiry_enquiry_referral_code_and_more'),
        ('payment', '0021_remove_commissionpayment_batch_and_more'),
        ('product', '0024_rename_lenghts_product_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
    migrations.CreateModel(
        name='MarketingPartnerAgreement',
        fields=[
            ('id', models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID'
            )),
            ('agreement_number', models.CharField(max_length=100, unique=True)),
            ('agreement_role', models.CharField(
                default='marketing_partner',
                max_length=100
            )),
            ('agreement_start_date', models.DateField()),
            ('agreement_end_date', models.DateField()),
            ('marketing_partner_name', models.CharField(max_length=255)),
            ('marketing_partner_address', models.TextField(blank=True, null=True)),
            ('profit_share_percentage', models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5
            )),
            ('selling_commission_percentage', models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5
            )),
            ('additional_points', models.TextField(blank=True, null=True)),
            ('qnx_mart_representative', models.CharField(
                blank=True,
                max_length=255,
                null=True
            )),
            ('qnx_mart_sign_s3_key', models.CharField(
                blank=True,
                max_length=500,
                null=True
            )),
            ('marketing_partner_sign_s3_key', models.CharField(
                blank=True,
                max_length=500,
                null=True
            )),
            ('qnx_mart_picture_s3_key', models.CharField(
                blank=True,
                max_length=500,
                null=True
            )),
            ('marketing_partner_picture_s3_key', models.CharField(
                blank=True,
                max_length=500,
                null=True
            )),
            ('uploaded_agreement_pdf_s3_key', models.CharField(
                blank=True,
                max_length=500,
                null=True
            )),
            ('remarks', models.TextField(blank=True, null=True)),
            ('status', models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('approved', 'Approved'),
                    ('rejected', 'Rejected')
                ],
                default='pending',
                max_length=20
            )),
            ('approved_at', models.DateTimeField(blank=True, null=True)),
            ('rejection_reason', models.TextField(blank=True, null=True)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('updated_at', models.DateTimeField(auto_now=True)),
            (
                'approved_by',
                models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='approved_marketing_partner_agreements',
                    to=settings.AUTH_USER_MODEL
                )
            ),
            (
                'created_by',
                models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_marketing_partner_agreements',
                    to=settings.AUTH_USER_MODEL
                )
            ),
            (
                'marketing_partner',
                models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='marketing_partner_agreements',
                    to='enquiry.marketingpartner'
                )
            ),
        ],
    ),

    migrations.CreateModel(
        name='CompanyAgreement',
        fields=[
            ('id', models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID'
            )),
            ('agreement_number', models.CharField(max_length=100, unique=True)),
            ('agreement_role', models.CharField(
                default='company',
                max_length=100
            )),
            ('apply_on_all_products', models.BooleanField(default=True)),
            ('agreement_start_date', models.DateField()),
            ('agreement_end_date', models.DateField()),
            ('company_owner_name', models.CharField(max_length=255)),
            ('company_address', models.TextField()),
            ('global_profit', models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True
            )),
            ('seller_adhar_number', models.CharField(
                blank=True,
                max_length=20,
                null=True
            )),
            ('owner_adhar_number', models.CharField(
                blank=True,
                max_length=20,
                null=True
            )),
            ('seller_pan_number', models.CharField(
                blank=True,
                max_length=20,
                null=True
            )),
            ('owner_pan_number', models.CharField(
                blank=True,
                max_length=20,
                null=True
            )),
            ('profit_share_percentage', models.DecimalField(
                decimal_places=2,
                max_digits=5
            )),
            ('selling_commission_percentage', models.DecimalField(
                decimal_places=2,
                max_digits=5
            )),
            ('additional_points', models.TextField(blank=True, null=True)),
            ('qnx_mart_representative', models.CharField(
                blank=True,
                max_length=255,
                null=True
            )),
            ('qnx_mart_sign_s3_key', models.CharField(
                blank=True,
                max_length=500,
                null=True
            )),
            ('company_sign_s3_key', models.CharField(
                blank=True,
                max_length=500,
                null=True
            )),
            ('qnx_mart_picture_s3_key', models.CharField(
                blank=True,
                max_length=500,
                null=True
            )),
            ('company_picture_s3_key', models.CharField(
                blank=True,
                max_length=500,
                null=True
            )),
            ('uploaded_agreement_pdf_s3_key', models.CharField(
                blank=True,
                max_length=500,
                null=True
            )),
            ('remarks', models.TextField(blank=True, null=True)),
            ('status', models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('approved', 'Approved'),
                    ('rejected', 'Rejected')
                ],
                default='pending',
                max_length=20
            )),
            ('approved_at', models.DateTimeField(blank=True, null=True)),
            ('rejection_reason', models.TextField(blank=True, null=True)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('updated_at', models.DateTimeField(auto_now=True)),
            (
                'approved_by',
                models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='approved_company_agreements',
                    to=settings.AUTH_USER_MODEL
                )
            ),
            (
                'company',
                models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='company_agreements',
                    to='company.company'
                )
            ),
            (
                'created_by',
                models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_company_agreements',
                    to=settings.AUTH_USER_MODEL
                )
            ),
        ],
    ),

    migrations.AlterField(
        model_name='agreementproduct',
        name='agreement',
        field=models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='agreement_products',
            to='agreement.companyagreement'
        ),
    ),

    migrations.AddConstraint(
        model_name='agreementproduct',
        constraint=models.UniqueConstraint(
            fields=('agreement', 'product'),
            name='unique_company_agreement_product'
        ),
    ),
]