# Generated by Django 5.2.11 on 2026-09-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0009_remove_companyagreement_global_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpartneragreement',
            name='company_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
