# Generated by Django 5.2.11 on 2026-09-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0010_marketingpartneragreement_company_commission_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpartneragreement',
            name='adhar_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='marketingpartneragreement',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
