# Generated by Django 5.2.11 on 2026-04-02 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='privacy_policy_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='terms_conditions_url',
        ),
    ]
