# Generated by Django 5.2.11 on 2026-04-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_company_privacy_policy_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='privacy_policy_url',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='terms_conditions_url',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
