# Generated by Django 5.2.11 on 2026-04-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_privacy_policy_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='privacy_policy_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='terms_conditions_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
