# Generated by Django 5.2.11 on 2026-04-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_privacy_policy_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='marketing_partner_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='referral_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='referral_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
