# Generated by Django 5.2.11 on 2026-04-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_marketing_partner_name_company_referral_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='referral_link',
        ),
        migrations.AlterField(
            model_name='company',
            name='referral_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
