# Generated by Django 5.2.11 on 2026-05-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_company_referral_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
