# Generated by Django 5.2.11 on 2026-05-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_company_payment_id_company_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
