# Generated by Django 5.2.11 on 2026-06-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_companypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_franchise_available',
            field=models.BooleanField(default=False),
        ),
    ]
