# Generated by Django 5.2.11 on 2026-06-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_company_is_franchise_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='accept_terms_conditions',
            field=models.BooleanField(default=False),
        ),
    ]
