# Generated by Django 5.2.11 on 2026-06-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_suppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_agreement_approved',
            field=models.BooleanField(default=False),
        ),
    ]
