# Generated by Django 5.2.11 on 2026-07-18 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_company_is_agreement_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_franchise_available',
        ),
    ]
