# Generated by Django 5.2.11 on 2026-07-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_remove_company_is_franchise_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_franchise_available',
            field=models.BooleanField(default=False),
        ),
    ]
