# Generated by Django 5.2.11 on 2026-07-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_company_is_franchise_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_franchise_available',
        ),
    ]
