# Generated by Django 5.2.11 on 2026-07-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_remove_company_is_franchise_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
