# Generated by Django 5.2.11 on 2026-08-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_company_pickup_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='shiprocket_pickup_location_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
