# Generated by Django 5.2.11 on 2026-08-08 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_company_shiprocket_pickup_location_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='shiprocket_pickup_location_id',
        ),
    ]
