# Generated by Django 5.2.11 on 2026-08-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_remove_company_shiprocket_pickup_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ISI_certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='ISO_certified',
            field=models.BooleanField(default=False),
        ),
    ]
