# Generated by Django 5.2.11 on 2026-08-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_company_isi_certified_company_iso_certified'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='COD_available',
            field=models.BooleanField(default=False),
        ),
    ]
