# Generated by Django 5.2.11 on 2026-09-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_company_cod_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='IAN_No',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
