# Generated by Django 5.2.11 on 2026-03-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Discount')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
