# Generated by Django 5.2.11 on 2026-03-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_alter_offer_discount_value_alter_offer_end_date_and_more'),
        ('product', '0015_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='offers', to='product.product'),
        ),
    ]
