# Generated by Django 5.2.11 on 2026-03-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_offer_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage Discount'), ('flat', 'Fixed Discount')], max_length=20, null=True),
        ),
    ]
