# Generated by Django 5.2.11 on 2026-03-29 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '__first__'),
        ('offer', '0004_alter_offer_offer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='company.company'),
        ),
    ]
