# Generated by Django 5.2.11 on 2026-03-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('offer', '0005_offer_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='branch',
            field=models.ManyToManyField(blank=True, related_name='offers', to='branch.branch'),
        ),
    ]
