from django.urls import path
from .views import( CancelOrderAPIView,
                   CancelPickupAPIView,
                   CreateShipOrderAPIView,
                   DownloadInvoiceAPIView,
                   DownloadLabelAPIView, 
                   DownloadManifestAPIView,
                   GenerateLabelAPIView,
                   GenerateManifestAPIView,
                   MyOrderDetailAPIView,
                   MyOrdersAPIView,
                   OrderCourierRatesAPIView, PackingVideoCreateAPIView, PackingVideoRetrieveAPIView,
                   PickupRequestAPIView, ReturnOrderAPIView,
                   ShipOrderListAPIView,
                   ShipOrderListCompanyAPIView, 
                   ShipmentListAPIView, 
                   ShippingRateAPIView, 
                   ShiprocketCreateOrderAPIView,
                   AssignAWBAPIView,
                   TrackShipmentAPIView,
                   ReturnShiprocketOrderAPIView,
                   AssignReturnAWBAPIView,
                   ReturnPickupRequestAPIView,
                   TrackReturnShipmentAPIView,
                   DownloadMultipleLabelsMultipleAPIView,
                   DownloadMultipleLabelsPDFAPIView
)
urlpatterns = [
    path("shipping-rates/", ShippingRateAPIView.as_view()),
    path("order-courier-rates/", OrderCourierRatesAPIView.as_view()),
    path("create-order/",CreateShipOrderAPIView.as_view(),name="create-order"),
    path("my-orders/",MyOrdersAPIView.as_view(),name="my-orders"),
    path("my-order-detail/",MyOrderDetailAPIView.as_view(),name="my-order-detail"),
    path("ship-orders/",ShipOrderListAPIView.as_view(),name="ship-order-list"),
    path("ship-orders-company/",ShipOrderListCompanyAPIView.as_view(),name="ship-order-list-company"),
    path("shiprocket-create-order/", ShiprocketCreateOrderAPIView.as_view(), name="shiprocket-create-order"),
    path("shipments/list/",ShipmentListAPIView.as_view(),name="shipment-list"),
    path("assign-awb/", AssignAWBAPIView.as_view(), name="assign-awb"),
    path("generate-label/",GenerateLabelAPIView.as_view(),name="generate-label"),
    path("pickup-request/",PickupRequestAPIView.as_view(),name="pickup-request"),
    path("track-shipment/",TrackShipmentAPIView.as_view(),name="track-shipment",),
    path("generate-manifest/",GenerateManifestAPIView.as_view(),name="generate-manifest"),
    path("cancel-order/",CancelOrderAPIView.as_view(),name="cancel-order",),
    path("cancel-pickup/",CancelPickupAPIView.as_view(),name="cancel-pickup",),
    path("download-label/",DownloadLabelAPIView.as_view(),name="download-label"),
    path("download-multiple-labels/",DownloadMultipleLabelsMultipleAPIView.as_view(),name="download-multiple-labels"),
    path("download-multiple-labels-pdf/",DownloadMultipleLabelsPDFAPIView.as_view(),name="download-multiple-labels-pdf"),
    path("packing-video/create/",PackingVideoCreateAPIView.as_view(),name="packing-video-create"),
    path("packing-video/retrieve/",PackingVideoRetrieveAPIView.as_view(),name="packing-video-retrieve"),
    path("download-invoice/",DownloadInvoiceAPIView.as_view(),name="download-invoice"),
    path("download-manifest/",DownloadManifestAPIView.as_view(),name="download-manifest"),
    path("return-order/",ReturnOrderAPIView.as_view(),name="return-order"),
    path("return-order/create-shipment/",ReturnShiprocketOrderAPIView.as_view(),name="return-create-shipment"),
    path("return-order/assign-awb/",AssignReturnAWBAPIView.as_view(),name="return-assign-awb"),
    path("return-order/pickup/",ReturnPickupRequestAPIView.as_view(),name="return-pickup"),
    path("return-order/track/",TrackReturnShipmentAPIView.as_view(),name="return-track"),
    ]