"""
Django settings for battery_manegement project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from datetime import timedelta
from pathlib import Path

import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0ih+62=%%7zh@97i-2y8z1itj!&k&mxb*^5kfz@o(1wm8vu47y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

CORS_ALLOW_ALL_ORIGINS = True
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'admin_profile',
    'company',
    'corsheaders',
    'product',
    'state',
    'offer',
    'enquiry',
    'accounts',
    'cart',
    'branch',
    'agreement',
    'core',
    'seller',
    'order',
    'Franchicies',
    'payment',
    'contact',
    'shiprocket',
    'olx',
    'real_estate',
    'loan',
    'AI',
    'commission',
    
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'battery_manegement.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'battery_manegement.wsgi.application'
GOOGLE_MAPS_API_KEY = "AIzaSyDAbR_hqIua2aM6lu9-il35vp3NNcsiFLk"

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
       'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'qnx_mart_6',
        'HOST': 'localhost',
        'PORT': '3306',
        'USER': 'root',
        'PASSWORD': 'root',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = "qnxmartb2b@gmail.com"
EMAIL_HOST_PASSWORD = "vjyf afdt oaah sxjp"

DEFAULT_FROM_EMAIL = "QNX Mart B2B <qnxmartb2b@gmail.com>"
import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


FIELD_ENCRYPTION_KEY = "XxYg3Q7aN5V2oR8xUuJ8lJ3iK4pQ0M8vK9zB2nF6LmA="

import os
from dotenv import load_dotenv # type: ignore

load_dotenv()
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME")
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"

# print("AWS_STORAGE_BUCKET_NAME:", AWS_STORAGE_BUCKET_NAME)
# print("AWS KEY:",AWS_ACCESS_KEY_ID)
# print("REGION:",AWS_S3_REGION_NAME)
# print("BUCKET:",AWS_STORAGE_BUCKET_NAME)


OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")


AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=1440),  # default 5 min → increase
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # default 1 day
    'AUTH_HEADER_TYPES': ('Bearer',),
}

RAZORPAY_KEY_ID = 'rzp_live_RqcU3IKenVsoyo'
RAZORPAY_KEY_SECRET = 'OXPd6UPiOkG9e1Fg6I7Ay2vR'
COMPANY_REGISTRATION_AMOUNT = 100


# settings.py

SHIPROCKET_EMAIL = "qnxmartb2b@gmail.com"
SHIPROCKET_PASSWORD = "DP7NkGoBp26*eW@vrR1niGJhVeU8EEg9"
SHIPROCKET_BASE_URL = "https://apiv2.shiprocket.in/v1/external"

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-shiprocket",
    }
}

# Redis cache configuration

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "protocol": 2,  # <-- Explicitly force RESP2 here
            }
        }
    }
}

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"





from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

FIREBASE_CREDENTIALS = (
    BASE_DIR
    / "battery_manegement"
    / "firebase"
    / "firebase-service-account.json"
)




WATI_API_URL = "https://live-mt-server.wati.io/10250882"
WATI_ACCESS_TOKEN = "wati_9c2e6e53-c311-4199-be6b-bebf87bbad0c.fJUNHgbfNpQBQaoPZwiiBb86DohYYUQBQ2E3OqkcCz68HQgggq2YRDmP7OioAg7LGjt93tEkdrhUNncKojg6ubN5rv5B-F4pgSZkki2oAyc15xbNTKuD7M45lfbCa-PT"