
from django.urls import path # type: ignore
from .views import (
                    AdminPendingProductListAPIView,
                    AllCategoryListAPIView,
                    ApproveProductAPIView,
                    ApprovedProductCountAPIView,
                    ApprovedProductListAPIView,
                    BrandBySubCategoryAPIView,
                    BrandCreateAPIView,
                    BrandListAPIView,
                    BrandallListAPIView,
                    BrandSoftDeleteAPIView,
                    BrandRestoreAPIView,
                    
                    CategoryByCompanyAPIView,
                    CategoryCreateAPIView,
                    CategoryUpdateAPIView,
                    CategoryListAPIView,
                    CategorynameListAPIView,
                    CategorySoftDeleteAPIView,
                    CategoryRestoreAPIView,
                    
                    BrandUpdateAPIView,
                    DeleteApprovedProductAPIView,
                    LatestApprovedProductAPIView,
                    LatestProductAPIViewAuth,
                    ProductActiveInactiveAPIView,
                    ProductCreateAPIView,
                    ProductDetailAPIView,
                    ProductListAPIView,
                    ProductListPendingAPIView,
                    ProductReferralLinkAPIView,
                    ProductSearchAPIView,
                    ProductsBySubCategoryAPI,
                    RecentlyViewedProductsAPIView,
                    # RecommendedProductAPIView,
                    RejectProductAPIView,
                    RelatedProductsView,
                    SubCategoryByCategoryAPIView,
                    SubCategoryCreateAPIView,
                    SubCategoryListAPIView,
                    SubCategoryUpdateAPIView,
                    UserProductUpdateRequestListAPIView,
                    UserSubCategoryListAPIView,
                    SubCategorySoftDeleteAPIView,
                    SubCategoryRestoreAPIView,
                    
                    TrackProductViewAPIView,
                    UnitCreateAPIView,
                    UnitSoftDeleteAPIView,
                    UnitRestoreAPIView,
                    UnitListAPIView,
                    UnitUpdateAPIView,
                    SubCategoryallListAPIView,
                    UnitRetrieveAPIView,
                    UnitallListAPIView,
                    LatestProductAPIView,
                    
                    CompanyProductListAPIView,
                    ProductUpdateRequestAPIView,
                    ApproveProductUpdateAPIView,
                    RejectProductUpdateAPIView,
                    ProductUpdateRequestListAPIView,
                    )



urlpatterns = [
    path('category/create/', CategoryCreateAPIView.as_view(), name='material-category-create'),
    path('category/update/', CategoryUpdateAPIView.as_view(), name='material-category-update'),
    path('category/list/',   CategoryListAPIView.as_view(),   name='material-category-list'), #filter by user
    path('category/names/',  CategorynameListAPIView.as_view(),   name='material-category-name-list'),
    path("category/all/", AllCategoryListAPIView.as_view(), name="all-category-list"),
    path('category/by-company/', CategoryByCompanyAPIView.as_view(), name='category-by-company'),
    path('category/soft-delete/', CategorySoftDeleteAPIView.as_view(), name='material-category-soft-delete'),
    path('category/restore/', CategoryRestoreAPIView.as_view(), name='material-category-restore'),

    path('subcategory/create/', SubCategoryCreateAPIView.as_view()),
    path('subcategory/list/', SubCategoryListAPIView.as_view()),
    path("subcategory/update/", SubCategoryUpdateAPIView.as_view(), name="subcategory-update"),
    path('subcategories/all/', SubCategoryallListAPIView.as_view(), name='subcategories-list'),
    path('subcategory/by-category/', SubCategoryByCategoryAPIView.as_view(), name='subcategory-by-category'),
    path('subcategory/by-user/list/', UserSubCategoryListAPIView.as_view(), name='subcategory-by-user'),
    path('subcategory/soft-delete/', SubCategorySoftDeleteAPIView.as_view(), name='subcategory-soft-delete'),
    path('subcategory/restore/', SubCategoryRestoreAPIView.as_view(), name='subcategory-restore'),
    path('products_by_subcategory/',ProductsBySubCategoryAPI.as_view()),
    
    path('api/brands/create/', BrandCreateAPIView.as_view(), name='brand-create'),
    path('api/brands/update/', BrandUpdateAPIView.as_view(), name='brand-update'),
    path('brand/list/', BrandListAPIView.as_view(), name='brand-list'),
    path('brand/all/', BrandallListAPIView.as_view(), name='brand-all-list'),
    path('brand/by-subcategory/', BrandBySubCategoryAPIView.as_view(), name='brand-by-subcategory'),
    path('brand/soft-delete/', BrandSoftDeleteAPIView.as_view(), name='brand-soft-delete'),
    path('brand/restore/', BrandRestoreAPIView.as_view(), name='brand-restore'),


    path('unit/create/', UnitCreateAPIView.as_view()),
    path('unit/list/', UnitListAPIView.as_view()),
    path('unit/all/', UnitallListAPIView.as_view()),
    path('unit/retrieve/', UnitRetrieveAPIView.as_view()),
    path('unit/update/', UnitUpdateAPIView.as_view()), 
    path('unit/soft-delete/', UnitSoftDeleteAPIView.as_view()),
    path('unit/restore/', UnitRestoreAPIView.as_view()),

    path('api/products/create/', ProductCreateAPIView.as_view(), name='product-create'),
    path('company/product/update-request/', ProductUpdateRequestAPIView.as_view(), name='product-update-request'),
    path('api/products/detail/', ProductDetailAPIView.as_view(), name='product-detail'),
    path('api/product/referral/', ProductReferralLinkAPIView.as_view(), name='product-referral-link'),
    path('api/products/list/', ProductListAPIView.as_view(), name='product-list'),
    path('pending-products/', AdminPendingProductListAPIView.as_view(), name='pending-products'),
    path('product/approved-list/', ApprovedProductListAPIView.as_view(), name='approved-product-list'),
    path('product/approve/', ApproveProductAPIView.as_view()),
    path('product/reject/', RejectProductAPIView.as_view()),
    path('approved_product_delete/', DeleteApprovedProductAPIView.as_view()),
    path("latest-products/", LatestProductAPIView.as_view(), name="latest-products"),
    path("company-latest-products/", LatestProductAPIViewAuth.as_view(), name="company-latest-products"),
    # path('products/company-latest-approved/', LatestApprovedProductAPIViewAuth.as_view(), name='company-latest-approved-products'),
    path('products/latest-approved/', LatestApprovedProductAPIView.as_view(), name='latest-approved-products'),
    path('approved-product-count/', ApprovedProductCountAPIView.as_view()),
    path('related_products/', RelatedProductsView.as_view()),
    path('product/search/', ProductSearchAPIView.as_view(), name='product-search'),
    path('product/recently-viewed/', RecentlyViewedProductsAPIView.as_view(), name='product-recently-viewed'),
    path('product/track-view/', TrackProductViewAPIView.as_view(), name='track-product-view'),
    path('company/products-list/', CompanyProductListAPIView.as_view(), name='company-product-list'),
    path('product/approve-update/', ApproveProductUpdateAPIView.as_view(), name='approve-product-update'),
    path("product-active-inactive/",ProductActiveInactiveAPIView.as_view(),name="product-active-inactive"),
    path('product/reject-update/', RejectProductUpdateAPIView.as_view(), name='reject-product-update'),
    path('product/update-request-list/', ProductUpdateRequestListAPIView.as_view(), name='product-update-request-list'),
    path('user/update-request-list/', UserProductUpdateRequestListAPIView.as_view(), name='user-product-update-request-list'),
    path('product/list_user/', ProductListAPIView.as_view(), name='product-list'),
    path('product/list_pending_user/', ProductListPendingAPIView.as_view(), name='product-list-pending'), #filter by user (pending list)
    path('products/latest_approved_user/', LatestApprovedProductAPIView.as_view(), name='latest-approved-products'),
    ]