from django.urls import path # type: ignore
from .views import (
                    ApprovedEnquiryList,
                    ApprovedEnquiryListAPIView,
                    ApprovedMarketingPartnerCountAPIView,
                    ApprovedMarketingPartnerListAPIView,
                    CompanyAdminLatestProductEnquiryListAPIView,
                    # CompanyAdminProductEnquiryListAPIView,
                    CompanyProductEnquiryListAPIView,
                    CompanyWiseEnquiryCountAPIView,
                    CompanyWiseProductEnquiryCountAPIView,
                    CompletedEnquiryListAPIView,
                    CompletedProductEnquiryListAPIView,
                    CompletedProductEnquiryAllListAPIView,
                    CreateBankDetailsAPIView,
                    CreateProductEnquiryAPIView,
                    EnquiryApproveRejectAPIView,
                    EnquiryCreateAPIView, 
                    EnquiryListAPIView, 
                    EnquirycountListAPIView, 
                    LatestUEnquiryListAPIView,
                    MarketingPartnerCompaniesAPIView, 
                    MarketingPartnerCreateAPIView, 
                    MarketingPartnerListAPIView,
                    MyProductEnquiryListAPIView,
                    PartnerCompaniesByIdAPIView,
                    ProductEnquiryCompleteCountAPIView,
                    ProductEnquiryCompleteUpdateAPIView,
                    ProductEnquiryCountAPIView,
                    ProductEnquiryDeliveredListAPIView,
                    ProductEnquiryDeliveredListAllAPIView,
                    ProductEnquiryDeliveredUpdateAPIView,
                    ProductEnquiryDispatchUpdateAPIView,
                    ProductEnquiryDispatchedRetrieveAPIView,
                    ProductEnquiryDispatchedRetrieveAllAPIView, 
                    RecentCompanyEnquiriesAPIView,
                    RetrieveBankDetailsAPIView,
                    SendToCompanyAPIView,
                    CompanyAdminProductEnquiryListAPIView,
                    SentToCompanyListAPIView, 
                    UenquiryCreateAPIView, 
                    UenquiryListAPIView, 
                    LatestEnquiryListAPIView,
                    MyMarketingProfileAPIView,
                    CompleteMarketingPartnerRegistrationAPIView,
                    MarketingHeadListAPIView,
                    MyReferredMarketingPartnersAPIView,
                    RejectMarketingPartnerAPIView,
                    ReferredMarketingPartnersAPIView,
                    MarketingHeadCompaniesAPIView,
                    CompanyWiseEnquiryCountAPIView,
                    UpdateBankDetailsAPIView
                    )

urlpatterns = [
    path('enquiry/create/', EnquiryCreateAPIView.as_view(), name='create-enquiry'),
    path("enquiry_list/", EnquiryListAPIView.as_view()),
    path("latest-enquiries/", LatestEnquiryListAPIView.as_view(), name='latest-enquiries'),
    
    
    path('create-enquiry/', UenquiryCreateAPIView.as_view(), name='create-enquiry'),
    path('uenquiry_list/', UenquiryListAPIView.as_view(), name='enquiry-list'),
    path("latest-uenquiries/", LatestUEnquiryListAPIView.as_view(), name='latest-uenquiries'),
    path('enquiry-count/', EnquirycountListAPIView.as_view(), name='enquiry-count'),
    path('product-enquiry/', CreateProductEnquiryAPIView.as_view()),
    # path('product-enquiry/', CreateBankDetailsAPIView.as_view()),
    path('product-enquiry-dispatch-update/',ProductEnquiryDispatchUpdateAPIView.as_view(),name='product-enquiry-dispatch-update'),
    path('product-enquiry-dispatched-list/',ProductEnquiryDispatchedRetrieveAPIView.as_view(),name='product-enquiry-dispatched-list'),
    path('product-enquiry/dispatched-all-list/',ProductEnquiryDispatchedRetrieveAllAPIView.as_view(),name='product-enquiry-dispatched-all-list'),
    
    path('product-enquiry-delivered-update/',ProductEnquiryDeliveredUpdateAPIView.as_view(),name='product-enquiry-delivered-update'),
    path('product-enquiry-delivered-list/',ProductEnquiryDeliveredListAPIView.as_view(),name='product-enquiry-delivered-list'),
    path('product-enquiry-delivered-all-list/',ProductEnquiryDeliveredListAllAPIView.as_view(),name='product-enquiry-delivered-all-list'),
    
    path('product-enquiry/update-complete-status/',ProductEnquiryCompleteUpdateAPIView.as_view(),name='product-enquiry-update-complete-status'),
    path('product-enquiry/completed-list/',CompletedProductEnquiryListAPIView.as_view(),name='completed-product-enquiry-list'),
    path('product-enquiry/completed-all-list/',CompletedProductEnquiryAllListAPIView.as_view(),name='completed-product-enquiry-all-list'),
    
    path('company-product-enquiries/', CompanyProductEnquiryListAPIView.as_view(), name='company-product-enquiries'),
    path('my_product-enquiries/', MyProductEnquiryListAPIView.as_view(), name='my-product-enquiries'),
    path('enquiry/send-to-company/', SendToCompanyAPIView.as_view()),
    path('enquiry/sent-list/', SentToCompanyListAPIView.as_view()),
    path('enquiry/approve-reject/', EnquiryApproveRejectAPIView.as_view()),
    path('enquiry/approved-list/', ApprovedEnquiryList.as_view()),
    path('approved-enquiry-list/',ApprovedEnquiryListAPIView.as_view(),name='approved-enquiry-list'),
    path('recent-company-enquiries/', RecentCompanyEnquiriesAPIView.as_view()),
    path('completed-enquiry-list/',CompletedEnquiryListAPIView.as_view(),name='completed-enquiry-list'),
    
    path('marketing-partner/create/', MarketingPartnerCreateAPIView.as_view(), name='partner-create'),
    path('marketing-partners/list/', MarketingPartnerListAPIView.as_view(), name='marketing-partner-list'),
    path('approved-marketing-partners/list/', ApprovedMarketingPartnerListAPIView.as_view(), name='approved-marketing-partner-list'),
    path('approved-marketing-partners/count/', ApprovedMarketingPartnerCountAPIView.as_view(), name='approved-marketing-partner-count'),
    path('bank-details/create/',CreateBankDetailsAPIView.as_view(),name='bank-details-create'),
    path('bank-details/update/',UpdateBankDetailsAPIView.as_view(),name='bank-details-update'),
    path('marketing-heads/list/', MarketingHeadListAPIView.as_view(), name='marketing-head-list'),
    path('retrieve-bank-details/',RetrieveBankDetailsAPIView.as_view(),name='retrieve-bank-details'),
    path('my-marketing-profile/', MyMarketingProfileAPIView.as_view(), name='my-marketing-profile'),
    path('my-referred-partners/', MyReferredMarketingPartnersAPIView.as_view(), name='my-referred-partners'),
    path('referred-partners/', ReferredMarketingPartnersAPIView.as_view(), name='referred-partners'),
    path('my-marketing-companies/',MarketingPartnerCompaniesAPIView.as_view(), name='my-marketing-companies'),
    path('marketing-head-companies/',MarketingHeadCompaniesAPIView.as_view(), name='marketing-head-companies'),
    path('partner-companies/', PartnerCompaniesByIdAPIView.as_view(), name='partner-companies-by-id'),
    
    path('partner/complete-registration/', CompleteMarketingPartnerRegistrationAPIView.as_view(), name='complete-partner-registration'),
    path('partner/reject/', RejectMarketingPartnerAPIView.as_view(), name='reject-marketing-partner'),
    
    # New API added, New Serializers added
    path('company/pending-product-enquiries/', CompanyAdminProductEnquiryListAPIView.as_view(), name='company-pending-product-enquiries'),
    path('company/latest-product-enquiries/', CompanyAdminLatestProductEnquiryListAPIView.as_view(), name='company-latest-product-enquiries'),
           
    path("product-enquiry/paid_unpaid_count/",ProductEnquiryCountAPIView.as_view(),name="product-enquiry-count",),
    path("company-wise-product-enquiry-count/",CompanyWiseProductEnquiryCountAPIView.as_view(),name="company-wise-product-enquiry-count",),
    path("company-wise-enquiry_complete-count/",CompanyWiseEnquiryCountAPIView.as_view(),name="company-wise-enquiry-count",),
    path("product-enquiry-complete-count/",ProductEnquiryCompleteCountAPIView.as_view(),name="product-enquiry-complete-count",),
]     


