# Generated by Django 5.2.11 on 2026-03-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0005_rename_discount_price_product_discount_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uenquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('product', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=200)),
                ('user_type', models.CharField(choices=[('personal', 'Personal'), ('business', 'Business'), ('organisation', 'Organisation')], max_length=20)),
                ('shop_name', models.CharField(blank=True, max_length=200, null=True)),
                ('firm_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contacts', models.JSONField(blank=True, null=True)),
                ('emails', models.JSONField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pincode', models.CharField(max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='enquiry_files/')),
                ('demo_required', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('demo_type', models.CharField(blank=True, choices=[('location', 'At Your Location'), ('online', 'Online'), ('center', 'At Center')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, to='product.product')),
            ],
        ),
    ]
