# Generated by Django 5.2.11 on 2026-03-18 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
        ('product', '0007_brand_category_brand_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_color', models.CharField(blank=True, max_length=50, null=True)),
                ('selected_size', models.CharField(blank=True, max_length=50, null=True)),
                ('selected_variant', models.CharField(blank=True, max_length=100, null=True)),
                ('person_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('pincode', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('message', models.TextField()),
                ('demo_required', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('demo_type', models.CharField(blank=True, choices=[('at_location', 'At Location'), ('online', 'Online')], max_length=20, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='enquiry_attachments/')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='product.product')),
            ],
        ),
    ]
