# Generated by Django 5.2.11 on 2026-04-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_productenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('aadhar_card', models.CharField(max_length=12)),
                ('pan_card', models.CharField(max_length=10)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='partner/profile/')),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('individual', 'Individual'), ('partnership', 'Partnership'), ('private_limited', 'Private Limited'), ('llp', 'LLP'), ('trust', 'Trust'), ('other', 'Other')], max_length=50)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('business_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('account_holder_name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('branch_name', models.CharField(blank=True, max_length=200, null=True)),
                ('channel_social_media', models.BooleanField(default=False)),
                ('channel_referral', models.BooleanField(default=False)),
                ('channel_online', models.BooleanField(default=False)),
                ('channel_events', models.BooleanField(default=False)),
                ('channel_other', models.BooleanField(default=False)),
                ('social_media_handles', models.TextField(blank=True, null=True)),
                ('target_audience', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_reach', models.CharField(blank=True, max_length=50, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('why_partner', models.TextField(blank=True, null=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
