# Generated by Django 5.2.11 on 2026-04-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0003_marketingpartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpartner',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='marketingpartner',
            name='referral_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
