# Generated by Django 5.2.11 on 2026-05-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0004_marketingpartner_referral_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingpartner',
            name='account_holder_name',
        ),
        migrations.RemoveField(
            model_name='marketingpartner',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='marketingpartner',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='marketingpartner',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='marketingpartner',
            name='ifsc_code',
        ),
    ]
