# Generated by Django 5.2.11 on 2026-05-08 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0005_remove_marketingpartner_account_holder_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingpartner',
            old_name='channel_events',
            new_name='otp_verified',
        ),
        migrations.RenameField(
            model_name='marketingpartner',
            old_name='target_audience',
            new_name='profession',
        ),
        migrations.RemoveField(
            model_name='marketingpartner',
            name='aadhar_card',
        ),
        migrations.RemoveField(
            model_name='marketingpartner',
            name='business_address',
        ),
        migrations.RemoveField(
            model_name='marketingpartner',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='marketingpartner',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='marketingpartner',
            name='channel_online',
        ),
        migrations.RemoveField(
            model_name='marketingpartner',
            name='channel_other',
        ),
        migrations.RemoveField(
            model_name='marketingpartner',
            name='channel_referral',
        ),
        migrations.RemoveField(
            model_name='marketingpartner',
            name='channel_social_media',
        ),
        migrations.RemoveField(
            model_name='marketingpartner',
            name='city',
        ),
        migrations.RemoveField(
            model_name='marketingpartner',
            name='estimated_reach',
        ),
        migrations.RemoveField(
            model_name='marketingpartner',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='marketingpartner',
            name='pan_card',
        ),
        migrations.RemoveField(
            model_name='marketingpartner',
            name='social_media_handles',
        ),
        migrations.RemoveField(
            model_name='marketingpartner',
            name='terms_accepted',
        ),
        migrations.RemoveField(
            model_name='marketingpartner',
            name='why_partner',
        ),
        migrations.AddField(
            model_name='marketingpartner',
            name='application_type',
            field=models.CharField(choices=[('marketing_head', 'Marketing Head'), ('marketing_partner', 'Marketing Partner')], default='marketing_partner', max_length=30),
        ),
        migrations.AddField(
            model_name='marketingpartner',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marketingpartner',
            name='promotion_platforms',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='marketingpartner',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_partners', to='enquiry.marketingpartner'),
        ),
        migrations.AddField(
            model_name='marketingpartner',
            name='taluka',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marketingpartner',
            name='team_size',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='marketingpartner',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_partner_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketingpartner',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marketingpartner',
            name='working_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='marketingpartner',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='marketingpartner',
            name='mobile',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='marketingpartner',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='marketingpartner',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketingpartner',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
