# Generated by Django 5.2.11 on 2026-05-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0006_rename_channel_events_marketingpartner_otp_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingpartner',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='marketingpartner',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
