# Generated by Django 5.2.11 on 2026-05-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0007_alter_marketingpartner_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uenquiry',
            name='is_sent_to_company',
            field=models.BooleanField(default=False),
        ),
    ]
