# Generated by Django 5.2.11 on 2026-05-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0008_uenquiry_is_sent_to_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='uenquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
