# Generated by Django 5.2.11 on 2026-05-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0009_uenquiry_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uenquiry',
            name='is_sent_to_company',
        ),
        migrations.RemoveField(
            model_name='uenquiry',
            name='status',
        ),
        migrations.AddField(
            model_name='productenquiry',
            name='is_sent_to_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productenquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
