# Generated by Django 5.2.11 on 2026-05-20 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0003_agreement_agreement_role_and_more'),
        ('company', '0009_companypayment'),
        ('enquiry', '0011_productenquiry_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('branch_name', models.CharField(blank=True, max_length=200, null=True)),
                ('account_number', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current')], default='savings', max_length=20)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marketing_partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='enquiry.marketingpartner')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingPartnerCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_company_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_fund_account_id', models.CharField(blank=True, max_length=200, null=True)),
                ('razorpay_payout_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agreement.agreement')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='company.company')),
                ('marketing_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='enquiry.marketingpartner')),
            ],
        ),
    ]
