# Generated by Django 5.2.11 on 2026-06-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0012_bankdetails_marketingpartnercommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='productenquiry',
            name='is_complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
