# Generated by Django 5.2.11 on 2026-06-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0013_productenquiry_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='productenquiry',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productenquiry',
            name='is_dispatched',
            field=models.BooleanField(default=False),
        ),
    ]
