# Generated by Django 5.2.11 on 2026-06-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0014_productenquiry_is_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productenquiry',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
