# Generated by Django 5.2.11 on 2026-07-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0016_productenquiry_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productenquiry',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productenquiry',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
