# Generated by Django 5.2.11 on 2026-07-08 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0017_productenquiry_is_paid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketingPartnerCommission',
        ),
    ]
