# Generated by Django 5.2.11 on 2026-07-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0018_delete_marketingpartnercommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpartner',
            name='enquiry_referral_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productenquiry',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
