# Generated by Django 5.2.11 on 2026-07-13 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0019_marketingpartner_enquiry_referral_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productenquiry',
            old_name='referral_code',
            new_name='enquiry_referral_code',
        ),
        migrations.RemoveField(
            model_name='marketingpartner',
            name='enquiry_referral_link',
        ),
    ]
