# Generated by Django 5.2.11 on 2026-07-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiprocket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='label_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
