# Generated by Django 5.2.11 on 2026-07-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiprocket', '0002_shipment_label_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='pickup_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
