# Generated by Django 5.2.11 on 2026-07-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiprocket', '0003_shipment_pickup_request_id_shipment_pickup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='manifest_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='tracking_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
