# Generated by Django 5.2.11 on 2026-08-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiprocket', '0004_shipment_manifest_url_shipment_tracking_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiporder',
            name='courier_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiporder',
            name='courier_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
