# Generated by Django 5.2.11 on 2026-08-20 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiprocket', '0005_shiporder_courier_id_shiporder_courier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiporder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('OUT_FOR_DELIVERY', 'Out For Delivery'), ('DELIVERED', 'Delivered'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURN_PICKUP', 'Return Pickup'), ('RETURN_IN_TRANSIT', 'Return In Transit'), ('RETURNED', 'Returned'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30),
        ),
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(max_length=50, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('reason', models.CharField(choices=[('DAMAGED', 'Product Damaged'), ('WRONG_PRODUCT', 'Wrong Product'), ('DEFECTIVE', 'Defective Product'), ('SIZE_ISSUE', 'Size Issue'), ('QUALITY_ISSUE', 'Quality Issue'), ('CUSTOMER_CHANGED_MIND', 'Customer Changed Mind'), ('OTHER', 'Other')], max_length=50)),
                ('reason_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('PICKUP_PENDING', 'Pickup Pending'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received'), ('REFUNDED', 'Refunded'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=30)),
                ('shiprocket_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('shipment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('awb_code', models.CharField(blank=True, max_length=100, null=True)),
                ('courier_company', models.CharField(blank=True, max_length=200, null=True)),
                ('tracking_url', models.URLField(blank=True, null=True)),
                ('pickup_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_status', models.CharField(default='Pending', max_length=100)),
                ('tracking_data', models.JSONField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_status', models.CharField(default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_orders', to='shiprocket.shiporder')),
            ],
        ),
    ]
