# Generated by Django 5.2.11 on 2026-04-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(choices=[('individual', 'Individual / Proprietorship'), ('partnership', 'Partnership'), ('llp', 'LLP'), ('private_limited', 'Private Limited'), ('public_limited', 'Public Limited')], max_length=50)),
                ('business_category', models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home', 'Home & Kitchen'), ('books', 'Books'), ('sports', 'Sports'), ('automotive', 'Automotive'), ('grocery', 'Grocery'), ('health', 'Health'), ('toys', 'Toys'), ('other', 'Other')], max_length=50)),
                ('contact_person_name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('alternate_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('landline', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField()),
                ('state', models.CharField(choices=[('MH', 'Maharashtra'), ('DL', 'Delhi'), ('KA', 'Karnataka'), ('TN', 'Tamil Nadu')], max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('bank_name', models.CharField(blank=True, max_length=150, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_certificate', models.FileField(blank=True, null=True, upload_to='seller_docs/')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='seller_docs/')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
