# Generated by Django 5.2.11 on 2026-08-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_seller_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='pan_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
