# Generated by Django 5.2.11 on 2026-08-23 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_seller_pan_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='gst_certificate',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='pan_card',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='pan_number',
        ),
    ]
