# Generated by Django 5.2.11 on 2026-04-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='address_line_1',
        ),
        migrations.AddField(
            model_name='order',
            name='address_line_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
