# Generated by Django 5.2.11 on 2026-05-06 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_rename_address_order_address_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_id',
            new_name='address',
        ),
    ]
