# Generated by Django 5.2.11 on 2026-05-06 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_rename_address_id_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
