# Generated by Django 5.2.11 on 2026-05-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='awb_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
