from django.urls import path

from .views import (
    BazaarAttributeCreateAPIView,
    BazaarAttributeListAPIView,
    BazaarCategoryListAPIView,
    BazaarEnquiryCreateAPIView,
    BazaarEnquiryListAPIView,
    BazaarListingCreateAPIView,
    BazaarListingListAPIView,
    BazaarListingDetailAPIView,
    BazaarListingUpdateAPIView,
    BazaarPlanCreateAPIView,
    BazaarPlanPricingListAPIView,
    BazaarPricingCreateAPIView,
    BazaarSubCategoryCreateAPIView,
    BazaarSubCategoryDeleteAPIView,
    BazaarSubCategoryListAPIView,
    MyBazaarListingAPIView,
    BazaarPlanListAPIView,
    BazaarCreatePaymentAPIView,
    BazaarVerifyPaymentAPIView,
    BazaarCategoryCreateAPIView
)

urlpatterns = [
    path("categories/create/",BazaarCategoryCreateAPIView.as_view(),name="admin-bazaar-category-create"),
    path("categories/", BazaarCategoryListAPIView.as_view(), name="bazaar-categories"),
    path("subcategories/create/",BazaarSubCategoryCreateAPIView.as_view(),name="bazaar-subcategory-create"),
    path("subcategories/",BazaarSubCategoryListAPIView.as_view(),name="bazaar-subcategory-list"),
    path("subcategories/delete/",BazaarSubCategoryDeleteAPIView.as_view(),name="bazaar-subcategory-delete"),
    path("attributes/create/",BazaarAttributeCreateAPIView.as_view(),name="bazaar-attribute-create"),
    path("attributes/",BazaarAttributeListAPIView.as_view(),name="bazaar-attribute-list"),
    path("listings/", BazaarListingListAPIView.as_view(), name="bazaar-listings"),
    path("listings/create/", BazaarListingCreateAPIView.as_view(), name="bazaar-listing-create"),
    path("listings/update/",BazaarListingUpdateAPIView.as_view(),name="bazaar-listing-update"),
    path("listings/detail/", BazaarListingDetailAPIView.as_view(), name="bazaar-listing-detail"),
    path("my-listings/", MyBazaarListingAPIView.as_view(), name="my-bazaar-listings"),
    path("plans/create/",BazaarPlanCreateAPIView.as_view(),name="bazaar-plan-create"),
    path("plans/", BazaarPlanListAPIView.as_view(), name="bazaar-plans"),
    path("pricing/create/",BazaarPricingCreateAPIView.as_view(),name="bazaar-pricing-create"),
    path("pricing/plans/", BazaarPlanPricingListAPIView.as_view(), name="bazaar-plan-pricing-list"),
    path("payment/create/", BazaarCreatePaymentAPIView.as_view(), name="bazaar-payment-create"),
    path("payment/verify/", BazaarVerifyPaymentAPIView.as_view(), name="bazaar-payment-verify"),
    path("enquiries/create/",BazaarEnquiryCreateAPIView.as_view(),name="bazaar-enquiry-create"),
    path("enquiries/",BazaarEnquiryListAPIView.as_view(),name="bazaar-enquiry-list"),
]