# Generated by Django 5.2.11 on 2026-03-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
