# Generated by Django 5.2.11 on 2026-03-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_product_variants_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image_s3_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
