# Generated by Django 5.2.11 on 2026-05-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_productupdaterequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='HSN_code',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
