# Generated by Django 5.2.11 on 2026-05-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_product_hsn_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='HSN_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
