# Generated by Django 5.2.11 on 2026-05-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_product_hsn_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='GST_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='HSN_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
