# Generated by Django 5.2.11 on 2026-07-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_franchise_available',
            field=models.BooleanField(default=False),
        ),
    ]
