# Generated by Django 5.2.11 on 2026-08-06 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_product_is_franchise_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='lenghts',
            new_name='length',
        ),
    ]
