# Generated by Django 5.2.11 on 2026-07-06 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agreement', '0006_agreement_uploaded_agreement_pdf_s3_key'),
        ('company', '0013_company_is_agreement_approved'),
        ('enquiry', '0016_productenquiry_total_amount_and_more'),
        ('product', '0021_product_gst_percent_alter_product_hsn_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('profit_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('razorpay_qr_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_payments', to='agreement.agreement')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_payments', to='company.company')),
                ('enquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_payment', to='enquiry.productenquiry')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_payments', to='product.product')),
            ],
        ),
    ]
