# Generated by Django 5.2.11 on 2026-07-06 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0006_agreement_uploaded_agreement_pdf_s3_key'),
        ('company', '0013_company_is_agreement_approved'),
        ('payment', '0001_initial'),
        ('product', '0021_product_gst_percent_alter_product_hsn_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='commissionpayment',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='commissionpayment',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='commissionpayment',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='commissionpayment',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='commissionpayment',
            name='razorpay_qr_id',
        ),
        migrations.RemoveField(
            model_name='commissionpayment',
            name='razorpay_signature',
        ),
        migrations.RemoveField(
            model_name='commissionpayment',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='commissionpayment',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='commissionpayment',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreement.agreement'),
        ),
        migrations.AlterField(
            model_name='commissionpayment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='commissionpayment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='commissionpayment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payment.commissionbatch'),
        ),
    ]
