# Generated by Django 5.2.11 on 2026-07-08 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0017_productenquiry_is_paid_and_more'),
        ('payment', '0003_commissionbatch_updated_at_commissionpayment_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionpayment',
            name='marketing_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enquiry.marketingpartner'),
        ),
        migrations.AddField(
            model_name='commissionpayment',
            name='marketing_partner_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='commissionpayment',
            name='marketing_partner_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
