# Generated by Django 5.2.11 on 2026-07-08 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0006_agreement_uploaded_agreement_pdf_s3_key'),
        ('company', '0013_company_is_agreement_approved'),
        ('enquiry', '0018_delete_marketingpartnercommission'),
        ('payment', '0004_commissionpayment_marketing_partner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionpayment',
            name='marketing_partner',
        ),
        migrations.RemoveField(
            model_name='commissionpayment',
            name='marketing_partner_commission',
        ),
        migrations.RemoveField(
            model_name='commissionpayment',
            name='marketing_partner_percentage',
        ),
        migrations.CreateModel(
            name='MarketingPartnerCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profit_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('marketing_partner_commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mp_commissions', to='agreement.agreement')),
                ('commission_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mp_commissions', to='payment.commissionpayment')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mp_commissions', to='company.company')),
                ('marketing_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mp_commissions', to='enquiry.marketingpartner')),
            ],
        ),
    ]
