# Generated by Django 5.2.11 on 2026-07-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_commissionpayment_marketing_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpartnercommission',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
