# Generated by Django 5.2.11 on 2026-07-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_marketingpartnercommission_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpartnercommission',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
