# Generated by Django 5.2.11 on 2026-07-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_marketingpartnercommission_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpartnercommission',
            name='selling_commission_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
