# Generated by Django 5.2.11 on 2026-07-16 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0007_remove_agreement_selle_radhar_number_and_more'),
        ('company', '0013_company_is_agreement_approved'),
        ('enquiry', '0020_rename_referral_code_productenquiry_enquiry_referral_code_and_more'),
        ('payment', '0008_marketingpartnercommission_selling_commission_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpartnercommission',
            name='commission_type',
            field=models.CharField(choices=[('selling', 'Selling Commission'), ('profit_share', 'Profit Share')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketingpartnercommission',
            name='enquiry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='partner_commissions', to='enquiry.productenquiry'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marketingpartnercommission',
            name='profit_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddConstraint(
            model_name='marketingpartnercommission',
            constraint=models.UniqueConstraint(fields=('commission_payment', 'commission_type'), name='unique_payment_commission_type'),
        ),
    ]
