# Generated by Django 5.2.11 on 2026-07-17 05:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0020_rename_referral_code_productenquiry_enquiry_referral_code_and_more'),
        ('payment', '0009_marketingpartnercommission_commission_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpartnercommission',
            name='wallet_credited',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MarketingPartnerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketing_partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='enquiry.marketingpartner')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingPartnerWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transaction', to='payment.marketingpartnercommission')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payment.marketingpartnerwallet')),
            ],
        ),
    ]
