# Generated by Django 5.2.11 on 2026-07-17 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0020_rename_referral_code_productenquiry_enquiry_referral_code_and_more'),
        ('payment', '0010_marketingpartnercommission_wallet_credited_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingPartnerWalletWithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketing_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_withdraw_requests', to='enquiry.marketingpartner')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_requests', to='payment.marketingpartnerwallet')),
            ],
        ),
    ]
