# Generated by Django 5.2.11 on 2026-07-17 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_marketingpartnerwalletwithdrawrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingpartnercommission',
            name='commission_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mp_commissions', to='payment.commissionpayment'),
        ),
        migrations.AlterField(
            model_name='marketingpartnercommission',
            name='commission_type',
            field=models.CharField(choices=[('selling', 'Selling Commission'), ('profit_share', 'Profit Share'), ('company_registration', 'Company Registration')], max_length=20),
        ),
    ]
