# Generated by Django 5.2.11 on 2026-07-17 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0020_rename_referral_code_productenquiry_enquiry_referral_code_and_more'),
        ('payment', '0012_alter_marketingpartnercommission_commission_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingpartnercommission',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_commissions', to='enquiry.productenquiry'),
        ),
    ]
