# Generated by Django 5.2.11 on 2026-07-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_paymentsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpartnerwalletwithdrawrequest',
            name='cheque_photo',
            field=models.ImageField(blank=True, null=True, upload_to='marketing_partner/cheques/'),
        ),
        migrations.AddField(
            model_name='marketingpartnerwalletwithdrawrequest',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
