# Generated by Django 5.2.11 on 2026-07-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_marketingpartnerwalletwithdrawrequest_paid_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpartnerwalletwithdrawrequest',
            name='paid_by_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
