# Generated by Django 5.2.11 on 2026-08-23 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_marketingpartnerwalletwithdrawrequest_paid_by_name'),
        ('shiprocket', '0006_alter_shiporder_status_returnorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpartnercommission',
            name='ship_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_partner_commissions', to='shiprocket.shiporder'),
        ),
    ]
