# Generated by Django 5.2.11 on 2026-08-23 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0007_remove_agreement_selle_radhar_number_and_more'),
        ('company', '0019_remove_company_shiprocket_pickup_location_id'),
        ('enquiry', '0020_rename_referral_code_productenquiry_enquiry_referral_code_and_more'),
        ('payment', '0018_marketingpartnercommission_ship_order'),
        ('product', '0024_rename_lenghts_product_length'),
        ('shiprocket', '0006_alter_shiporder_status_returnorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipOrderCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('commission_type', models.CharField(choices=[('selling', 'Selling Commission'), ('profit_share', 'Profit Share')], max_length=20)),
                ('commission_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('wallet_credited', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_order_commissions', to='agreement.agreement')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_order_commissions', to='company.company')),
                ('marketing_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_order_commissions', to='enquiry.marketingpartner')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_order_commissions', to='product.product')),
                ('ship_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='shiprocket.shiporder')),
            ],
        ),
    ]
